name: Expressions

on:
  push:

jobs:
  sample1:
    name: sample 1
    runs-on: ubuntu-latest
    steps:
      - name: contains true
        if: contains(fromJSON('["one", "two"]'), 'one')
        run: echo "true"
      - name: format
        if: format('Hello {0} {1}', 'Tom', 'World') == 'Hello Tom World'
        run: echo 'Hello Tom World'
  sample2:
    name: sample 2
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"}, {\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  sample3:
    needs: sample2
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.sample2.outputs.matrix) }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
