name: Expressions

on:
  push:

jobs:
  sample1:
    name: sample 1
    runs-on: ubuntu-latest
    steps:
      - name: contains true
        run: contains(fromJSON('["one", "two"]'), 'one')
      - name: contains false
        run: contains(fromJSON('["one", "two"]'), 'three')
