name: production

env:
  TZ: Asia/Tokyo

on:
  push:

jobs:
  get_current_time:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      current_time: ${{ steps.current_time_id.outputs.current_time_value }}
    steps:
      - id: current_time_id
        run: echo "current_time_value=$(date + '%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
  prd_process:
    needs:
      - get_current_time
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      env: prd
      current_time: ${{ needs.get_current_time.outputs.current_time }}
    secrets:
      ENVIRONMENTS_SECRET_1: ${{ secrets.ENVIRONMENTS_SECRET_1 }}
      ENVIRONMENTS_VARIABLE_1: ${{ secrets.ENVIRONMENTS_VARIABLE_1 }}
      REPOSITORY_SECRETS_1: ${{ secrets.REPOSITORY_SECRETS_1 }}
